print("Operasi Boolean And ==")
print("True ==/and True   : |",True == True)
print("True ==/and False  : |",True == False)
print("False ==/and True  : |",False == True)
print("False ==/and False : |",False == False)

print("Operasi Boolean or EXOR !=")
print("True ==/and True   : |",True != True)
print("True ==/and False  : |",True != False)
print("False ==/and True  : |",False != True)
print("False ==/and False : |",False != False)

print("Operasi Boolean NAND | ")
print("True ==/and True   : |",True | True)
print("True ==/and False  : |",True | False)
print("False ==/and True  : |",False | True)
print("False ==/and False : |",False | False)